'''
Here we setup initial migrations for the project.

DEV/TEST USE ONLY - never run this against a real database (staging/production/anything with
data or a migration history worth keeping). reset_database() drops every table and enum type,
and reset_migrations() DELETES every migration file on disk before collapsing the schema into one
freshly autogenerated "Initial migration". Autogenerate only diffs SQLAlchemy model metadata
(tables/columns/indexes/enums) - it has no way to see hand-written raw-SQL migrations
(op.execute(...) - e.g. the NOTIFY trigger migrations), so those are silently lost, not
regenerated. This exact mistake broke production's Postgres LISTEN/NOTIFY -> SSE pipeline once
already (see 0248de142b32_restore_container_status_and_save_notify_triggers.py's own docstring).

To bring up a brand-new database that must end up with the REAL, current schema (staging,
production, or just a fresh clone you want history-accurate) use `python upgrade.py upgrade`
instead - it replays the actual migration chain via `alembic upgrade head`, which correctly
re-applies every historical op.execute() migration in order.
'''

# builtins
from dotenv import load_dotenv
import os

# local
from browseterm_db.common.config import DBConfig
from browseterm_db.migrations.migrator import Migrator
from browseterm_db.common.config import MIGRATIONS_DIR
from db_state_manager.state_manager import (
    DBStateManager,
    update_subscription_types,
    update_images
)

# load the environment variables
load_dotenv('.env')


class SetupInitialMigrations():
    '''
    Setup the initial migrations.
    '''
    def __init__(self) -> None:
        self.db_config: DBConfig = DBConfig(
            username=os.getenv('DB_USERNAME'),
            password=os.getenv('DB_PASSWORD'),
            host=os.getenv('DB_HOST'),
            port=int(os.getenv('DB_PORT')),
            database=os.getenv('DB_DATABASE')
        )
        self.migrator: Migrator = Migrator(self.db_config, MIGRATIONS_DIR)
        self.migrator.reset_database()  # reset the database
        # delete all files in the versions directory
        self.migrator.reset_migrations()
        self.db_state_manager: DBStateManager = DBStateManager(self.db_config)

    def setup(self) -> None:
        '''
        Setup the initial migrations.
        '''
        # create all tables
        self.migrator.revision('Initial migration')
        # upgrade the database
        self.migrator.upgrade()

        # seed data from JSON files
        print("Creating subscription types from JSON...")
        update_subscription_types(self.db_state_manager)
        print("Creating images from JSON...")
        update_images(self.db_state_manager)
        print("Database seeding complete.")


if __name__ == "__main__":
    setup_initial_migrations = SetupInitialMigrations()
    setup_initial_migrations.setup()
