"""added kubernetes_id and saved_image to containers model

Revision ID: 093e4526fa42
Revises: 7b11102e715c
Create Date: 2025-10-26 00:58:38.835853

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '093e4526fa42'
down_revision = '7b11102e715c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('kubernetes_id', sa.String(length=255), nullable=True))
    op.add_column('containers', sa.Column('saved_image', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'saved_image')
    op.drop_column('containers', 'kubernetes_id')
    # ### end Alembic commands ###
