"""Add storage_limit and associated_resources to containers, add storage_limit_per_container to subscription_types

Revision ID: 0f7f0ca831a6
Revises: a1b2c3d4e5f6
Create Date: 2025-12-19 18:27:16.292727

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0f7f0ca831a6'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('storage_limit', sa.String(length=20), nullable=False, server_default='2Gi'))
    op.add_column('containers', sa.Column('associated_resources', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('subscription_types', sa.Column('storage_limit_per_container', sa.String(length=20), nullable=False, server_default='2Gi'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_types', 'storage_limit_per_container')
    op.drop_column('containers', 'associated_resources')
    op.drop_column('containers', 'storage_limit')
    # ### end Alembic commands ###
