"""added ip address to containers model

Revision ID: 7b11102e715c
Revises: bfd5b51ab8dc
Create Date: 2025-10-21 00:19:12.458905

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '7b11102e715c'
down_revision = 'bfd5b51ab8dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
