"""Add ip_address to containers table

Revision ID: bfd5b51ab8dc
Revises: f0864ed250cd
Create Date: 2025-10-20 23:56:51.266371

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'bfd5b51ab8dc'
down_revision = 'f0864ed250cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('ip_address', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('containers', 'ip_address')
    # ### end Alembic commands ###
