"""added images table

Revision ID: f0864ed250cd
Revises: c1025f963d00
Create Date: 2025-10-20 11:24:02.194118

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f0864ed250cd'
down_revision = 'c1025f963d00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_image_is_active', 'images', ['is_active'], unique=False)
    op.create_index('idx_image_name', 'images', ['name'], unique=False)
    op.create_index(op.f('ix_images_name'), 'images', ['name'], unique=True)
    op.add_column('containers', sa.Column('image_id', sa.UUID(), nullable=True))
    op.create_index('idx_container_image_id', 'containers', ['image_id'], unique=False)
    op.create_foreign_key(None, 'containers', 'images', ['image_id'], ['id'], ondelete='SET NULL')
    op.drop_column('containers', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('containers', sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'containers', type_='foreignkey')
    op.drop_index('idx_container_image_id', table_name='containers')
    op.drop_column('containers', 'image_id')
    op.drop_index(op.f('ix_images_name'), table_name='images')
    op.drop_index('idx_image_name', table_name='images')
    op.drop_index('idx_image_is_active', table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
