"""add last_active_at column to containers

Revision ID: f6a7b8c9d0e1
Revises: e5f6a7b8c9d0
Create Date: 2026-07-23

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a7b8c9d0e1'
down_revision = 'e5f6a7b8c9d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Activity tracking for the idle reaper: timestamp of the container's last user activity
    # (stamped by socket-ssh on WS connect / heartbeat / disconnect). Hand-written rather than
    # autogenerated so the container-status / save-status NOTIFY triggers are preserved.
    op.add_column('containers', sa.Column('last_active_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    op.drop_column('containers', 'last_active_at')
